### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by pfrandsen** [sean3z/angular-activity-monitor#1]
Please add version tags such that specific versions can be identified in bower.json files. We need to be able to reference specific versions instead of just head (which would potentially be unpredictable unless you reference a specific commit hash).

**Comment by sean3z** [comment]
Major oversight on my part; thanks for pointing this out!
I've added a [`0.1.0`](https://github.com/sean3z/angular-activity-monitor/releases/tag/v0.1.0) tag which can now be targeted for installation

**Comment by pfrandsen** [comment]
Thanx Sean. Great component by the way :-)
