### ISSUE TITLE
Provider for angular.config()

### ISSUE THREAD

**Issue by sassrobi** [sean3z/angular-activity-monitor#13]
It would be nice if I can configure this service in the angular.config() section, where other service providers got configured (for example $logProvider, $translateProvider, etc.)

**Comment by sean3z** [comment]
That's an excellent idea @sassrobi! 

I'm not really actively maintaining this project as I believe most of the community has moved on to Angular versions > 1. However, I really like this idea and work towards it unless you'd like to submit a pull request 😃

**Comment by sassrobi** [comment]
> unless you'd like to submit a pull request 

Not likely, sorry. By the time, i realised that i need to reconfigure this module "runtime", so it works for me as it is now. Apart from that, this would be a nice feature. 😄 

> I believe most of the community has moved on to Angular versions > 1

IMHO this is not the case, many Angular 1.x applications exists, and moving to 2.x is not trivial. We are using angular 1.x for new projects too.
