### ISSUE TITLE
Inactive/warning firing unexpectedly after computer resumes from sleep

### ISSUE THREAD

**Issue by trdyer** [sean3z/angular-activity-monitor#14]
When my computer resumes from sleep I am getting the warning method firing, regardless of whether the event should have fired or not.

Sometimes even after I have been logged out/ and i have called `ActivityMonitor.off('inactive')`

Is there a known issue with this?

**Comment by trdyer** [comment]
In particular I have a session expiry warning modal/logout function. I am `off`ing the functions when a user is logged out. if at that point the computer is put to sleep and later resumed then the user logs back in they immediately see the warning pop-up. I think it may be triggered because the value of ActivityMonitor.user.action is not being re-initialized.

**Comment by sean3z** [comment]
Hey @trdyer, thanks for pointing this out! I'm not actively working on this project anymore but, will certainly take a look to see what could be causing this issue! 

Just to ensure I can replicate using the same environment, what version of Angular are you using?

**Comment by trdyer** [comment]
hey sorry, for some reason my notifications didn't come through... we are on angular 1.6.5

**Comment by Mrjaid** [comment]
any update on this??

**Comment by Mrjaid** [comment]
Do you have any destroy or re-init function that could be called on resume?
