### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by anterokarttunen** [sean3z/angular-activity-monitor#3]
angularjs version: AngularJS v1.2.25

``` js
var module = angular.module('derp.module', [
    'ActivityMonitor'
  ])
  .controller('derpController', function (ActivityMonitor) {
    ActivityMonitor.options.enabled = true;
    ActivityMonitor.options.inactive = 10;
    ActivityMonitor.options.warning = 5;
    ActivityMonitor.on('inactive', function() {
      alert('user is inactive');
    });
    ActivityMonitor.on('keepAlive', function() {
    });
    ActivityMonitor.on('warning', function() {
      alert('warning session is timing out');
    });
```

**Comment by sean3z** [comment]
Thanks @anterokarttunen! 
Could you provide more insight into what exactly isn't working? 
Do you get any console errors? 
Any additional information that may help track down the issue?

**Comment by sean3z** [comment]
Tested thoroughly with Angular [`v1.2.25`](https://code.angularjs.org/1.2.25/angular.min.js) and works as expected. 
With no reply in 25 days, I'm going to close this issue

**Comment by gslender** [comment]
I can't get it to work either. Using AngularJS v1.5.3
