### ISSUE TITLE
Is there a reason not to keep the activity monitor alive?

### ISSUE THREAD

**Issue by sankargorthi** [sean3z/angular-activity-monitor#8]
The current code will disable the activity monitor when the first [instance of inactivity](https://github.com/sean3z/angular-activity-monitor/blob/master/activity-monitor.js#L106) is encountered. Is that for a particular reason?

**Comment by sean3z** [comment]
For my use case, I didn't want to keepAlive any items in the background once the user was considered inactive. Additionally, I didn't want to continuously fire `inactive` events. 

Do you have a need for those things or are you implying that the service should "reset" after the first instance of inactivity?

**Comment by sankargorthi** [comment]
We have a long-polling request (which fires off every 10seconds) on our webapp that I'd like to disable after the user is inactive for a few minutes. If they come back within a reasonable amount of time, I'd like to restore the long-polling request.

Should I use a different pattern than the one I've proposed?

**Comment by sean3z** [comment]
@sankargorthi Thanks for the insight! Do you feel as if this could be accomplished by just exposing the `enable` and `disable` methods for manual use?

**Comment by sankargorthi** [comment]
No, I think that would mean having to explicitly invoke the `enable`/`disable` methods. Seems non-intuitive. Having a config parameter control the process and letting `ActivityMonitor` do the heavy lifting seems more appropriate.

**Comment by AckerApple** [comment]
I need a "fix" on this as well. My suggestion is to add property "disableOnInactive" which default it true. But for my needs and @sankargorthi, we will set disableOnInactive to false.

Then on line 108, do not call disable. Additional modifications maybe required to prevent double calls to inactive and such.

**Comment by AckerApple** [comment]
I have issued a pull request that I spent some quality time on for this issue. Do hope this pull request can be satisfied in a timely manner. Thank you kindly

https://github.com/sean3z/angular-activity-monitor/pull/10

**Comment by AckerApple** [comment]
Adjusted PR to address repeat calls during inactivity

**Comment by sean3z** [comment]
Fixed in the PR mentioned above, thanks all!
